### ISSUE TITLE
Link to OpenEvals for professors and courses

### ISSUE THREAD

**Issue by NathanCastle** [ComputerScienceHouse/schedulemaker#108]
This should be relatively straightforward. URLs are in the form openevals.rit.edu/course/category/number. 

e.g. CSCI-141: https://openevals.rit.edu/course/CSCI/141

Professors are in the form openevals.rit.edu/professor/lastname/firstname:

e.g. Aaron Deever: https://openevals.rit.edu/professor/Deever/Aaron

**Comment by JoelEager** [comment]
Thanks for posting this; I'll bring it up with Ben.

**Comment by devinmatte** [comment]
I am working to implement this in some form to Schedulemaker. The issue I'm coming up with isn't implementing it to Schedulemaker, but that OpenEvals is kinda broken still.

For example, when you attempt to pull results for a professor that exists in the school, but doesn't have a valid route in OpenEvals it will return a straight 404 like this: https://openevals.rit.edu/professor/Tymann/Paul/

Obviously it's not on us to ensure that OpenEvals works, but I'd rather not be sending people to a lot of 404s

**Comment by NathanCastle** [comment]
Perhaps the SG folks can set up an endpoint for verifying if a professor or course exists. That would be trivial for them to set up and it would allow you to not show URLs that will 404. Have you been in contact with them?

**Comment by devinmatte** [comment]
I haven't been in contact, I'm likely going to put in an issue on their repository before I work on this tonight. It is open source, so I may just find a way to build that in myself.

I definitely want to check instead of just sending people to 404s, however I don't want to make extra requests every time we load a schedule to check every link to see if it 404s or not before displaying the option.

I'm going to be working on this during the Hackathon tonight, and I'll try to come up with a solution.

**Comment by devinmatte** [comment]
Openevals appears to no longer be open source, because of that I'm not sure if I can utilize the data apart from simply linking to the pages and hoping we're not sending them to a 404.
I would really like to implement it in a cleaner way

**Comment by Mstrodl** [comment]
OpenEvals is dead
