### ISSUE TITLE
Fatal Error only resolved when eliminating all but one lab

### ISSUE THREAD

**Issue by jackhickson** [ComputerScienceHouse/schedulemaker#118]
An Fatal Error appears if only in my EEEE course more than one lab is selected.
![image](https://cloud.githubusercontent.com/assets/12489245/20334977/77c2f8ca-ab8c-11e6-8ada-89325e46b588.png)
![image](https://cloud.githubusercontent.com/assets/12489245/20334987/8a3f7cee-ab8c-11e6-9f9b-e1c363b17da6.png)

If only one is selected it will generate a schedule
![image](https://cloud.githubusercontent.com/assets/12489245/20334992/99934676-ab8c-11e6-9176-d2cfe9e95df3.png)
![image](https://cloud.githubusercontent.com/assets/12489245/20334996/a744132c-ab8c-11e6-9ea4-68664d8fedfc.png)

No other option are interfering with the result besides my class list
![image](https://cloud.githubusercontent.com/assets/12489245/20334959/5259c398-ab8c-11e6-8679-8daa9fc92458.png)

**Comment by bgrawi** [comment]
This is due to the sheer number of schedules generated. Generally we can only handle about 10,000-20,000 possible schedules. All of your schedules up to this point generate more than 11,000. After adding those thirteen sections, this number becomes 150,000 schedules, where the last 11,000 schedules wold have the class in the lab selected. The only solution is to narrow down the results ahead of time or add times you don't want classes. Plus you don't actually want to look through hundreds of thousands of schedules anyway.
