### ISSUE TITLE
Can't see classroom on schedule without mouse over.

### ISSUE THREAD

**Issue by joegiants182** [ComputerScienceHouse/schedulemaker#119]
Make box larger to fit classroom on schedule, or make text smaller to make classroom fit. Just a nice to have feature Id thought id suggest.

**Comment by stevenmirabito** [comment]
Just to make sure we're on the same page you're talking about this behavior, right?

![](https://content.screencast.com/users/steven_mirabito/folders/Snagit/media/5221b6a4-f32b-49c4-8b35-5b715ec4e077/2017-01-24_09-21-54.gif)

I believe that was implemented that way to fit as many classes on the calendar without taking up a large amount of vertical space, and so that the schedule blocks were sized based on time, not content. Thoughts @bgrawi or @JoelEager?

Just so you know, you can also change the order that class information is displayed on the schedule by playing with the settings at the bottom of the page:

![](https://content.screencast.com/users/steven_mirabito/folders/Snagit/media/9bd1d580-d038-4811-b06b-d8663e509762/2017-01-24_09-24-18.png)

**Comment by joegiants182** [comment]
Welp. you can close this. I didn't realize those were all the same choices, just different order at first glance... Thanks for answering quickly!

**Comment by stevenmirabito** [comment]
No problem, glad I could help.
