### ISSUE TITLE
Adding "ACSC 10" creates internal server error on generate schedule

### ISSUE THREAD

**Issue by Milkshak3s** [ComputerScienceHouse/schedulemaker#122]
Returns a "Fatal Error: An internal server error occurred" when attemping to generate a schedule with the "ACSC 10" course. Returns to normal when course is removed.

*EDIT* Or maybe just when adding more than 3 classes.

**Comment by mbillow** [comment]
The problem is with the number of sections. With 136 different sections, your number of possible different schedule options are incredibly high and it doesn't make sense to compute them all. If you pick just a couple meeting times you want, everything should work fine. Let us know if you have any more issues.

**Comment by sman591** [comment]
I think having schedulemaker notice this and display a warning, rather than a server error, would help a lot. Or even set a max # of schedules that it's allowed to generate.

**Comment by bgrawi** [comment]
Consolidating in #133.
